import { Question } from './types';

export const QUESTIONS: Question[] = [
  // --- CONNECTION & DEEP QUESTIONS ---
  { id: 1, text: "Am I Avoiding Any Hard Conversations With Myself? If So, What Comes To Mind?" },
  { id: 2, text: "Am I Like You Expected Me To Be?" },
  { id: 3, text: "Am I Someone You Typically Connect With?" },
  { id: 4, text: "Are Any Of My Insecurities Hurting Anyone Else By Accident?" },
  { id: 5, text: "Are You Lying To Yourself About Anything?" },
  { id: 6, text: "Are You Missing Anyone Right Now? Do You Think They Are Missing You Too?" },
  { id: 7, text: "Are You Proud Of Yourself?" },
  { id: 8, text: "Based On What You Learned About Me, What Book Would You Recommend I Read?" },
  { id: 9, text: "Between The Two Of Us, Who Do You Think Is Quicker At Responding To Emails?" },
  { id: 10, text: "Describe A Dream That You've Had Recently." },
  { id: 11, text: "Describe The First Time We Met Through Your Perspective In Detail." },
  { id: 12, text: "Describe Your Perfect Date." },
  { id: 13, text: "Describe Your Worst Heartbreak. What Did It Teach You?" },
  { id: 14, text: "Did You Ever Stalk My Social Media Before We Met? If So, What Stood Out?" },
  { id: 15, text: "Do I Have A Clear Picture Of Who I Want To Be This Time Next Year?" },
  { id: 16, text: "Do I Intimidate You? Why Or Why Not?" },
  { id: 17, text: "Do I Seem Like A Cat Or Dog Person?" },
  { id: 18, text: "Do I Seem Like A Morning Person Or A Night Owl? Why?" },
  { id: 19, text: "Do You Believe In 'Right Person, Wrong Timing'?" },
  { id: 20, text: "Do You Believe In Second Chances? Why Or Why Not?" },
  { id: 21, text: "Do You Think I Ever Checked An Ex's Phone For Evidence?" },
  { id: 22, text: "Do You Think I Fall In Love Easily? Why Or Why Not?" },
  { id: 23, text: "Do You Think I Intimidate Others? Why Or Why Not?" },
  { id: 24, text: "Do You Think I'm Still On Good Terms With My Exes? Why Or Why Not?" },
  { id: 25, text: "Do You Think I've Ever Had My Heart Broken?" },
  { id: 26, text: "Do You Want Closure Or Just An Excuse To Talk To Them? Explain." },
  { id: 27, text: "Finish The Sentence: Dating Is __________. Both Players." },
  { id: 28, text: "Finish The Sentence: I Know I've Forgiven Someone When _________." },
  { id: 29, text: "Finish The Sentence: I'm Proudest Of You For _________." },
  { id: 30, text: "Finish The Sentence: Strangers Would Describe Me As ______ Only I Know That I Am _______." },
  { id: 31, text: "Has A Stranger Ever Changed Your Life?" },
  { id: 32, text: "Have I Ever Betrayed Your Trust In Any Big Or Small Way? What Would Help Rebuild That Trust?" },
  { id: 33, text: "Have You Ever Fallen In Love?" },
  { id: 34, text: "How Can I Add 1% More Happiness To Your Life?" },
  { id: 35, text: "How Do You Define Forgiveness?" },
  { id: 36, text: "How Many Speeding Tickets Do You Think I've Gotten In My Life?" },
  { id: 37, text: "If You Could Go Back In Time, Would You Change Something From Your Past?" },
  { id: 38, text: "If You Could Have Any Food In The World Right Now, What Would It Be?" },
  { id: 39, text: "If You Were To Buy Me A Present, Knowing Nothing About Me Other Than What I Look Like, What Would It Be?" },
  { id: 40, text: "Is There Anyone You Think You've Hurt?" },
  { id: 41, text: "What About Me Surprised You?" },
  { id: 42, text: "What Are You Currently Healing From That Others Don't See?" },
  { id: 43, text: "What Do You Need To Hear Right Now?" },
  { id: 44, text: "What Is The Hardest Truth You Had To Face This Year?" },
  { id: 45, text: "What Would Make You Feel Closer To Me?" },
  { id: 46, text: "When Was The Last Time You Cried And Why?" },
  { id: 47, text: "Who In Your Life Do You Need To Set Better Boundaries With?" },
  { id: 48, text: "What's A Boundary You Can Set With Yourself Today That Will Benefit Future You?" },
  { id: 49, text: "What's My Biggest Pet Peeve? Explain." },
  { id: 50, text: "What Is Your Most Toxic Trait You Can Admit To?" },
  { id: 51, text: "What Is The Last Thing You Lied To Your Mother About?" },
  { id: 52, text: "Who Do You Think My Celebrity Crush Is?" },
  { id: 53, text: "What Song Best Describes Our Relationship?" },
  { id: 54, text: "What Impression Do You Think I Give To Strangers?" },
  { id: 55, text: "If We Were In A Band, What Would Our Name Be?" },
  { id: 56, text: "What Are You Overthinking Right Now?" },
  { id: 57, text: "What Is A Dream You've Let Go Of?" },
  { id: 58, text: "When Was The Last Time You Felt Truly Understood By Somebody?" },
  { id: 59, text: "What Part Of Your Job Energizes You The Most? What Drains You?" },
  { id: 60, text: "What Is Something You Wouldn't Want To Change About Yourself?" },
  { id: 61, text: "How Old Do You Feel Emotionally?" },
  { id: 62, text: "What Are You Most Grateful For In This Current Moment?" },
  { id: 63, text: "What Are You Still Trying To Prove To Yourself?" },
  { id: 64, text: "Who In Your Life Deserves The Biggest Thank You?" },
  { id: 65, text: "What Purchase Has Meant The Most To You Recently?" },
  { id: 66, text: "When Was The Last Time You Pleasantly Surprised Yourself?" },
  { id: 67, text: "How Do You Treat Yourself When You've Made A Mistake?" },
  { id: 68, text: "Do You Think I'm Usually Early, On Time, Or Late To Events?" },
  { id: 69, text: "What Do You Think My Perfect Date Night Would Be?" },
  { id: 70, text: "What Lesson Took You The Longest To Unlearn?" },

  // --- WILDCARDS ---
  { id: 100, text: "All Players Close Your Eyes. What Color Are My Eyes?", wildcard: true },
  { id: 101, text: "All Players Close Your Eyes. What Color Is My Shirt?", wildcard: true },
  { id: 102, text: "All Players Rate Each Player's Communication Skills On A Scale Of 1-10.", wildcard: true },
  { id: 103, text: "All Players Share Something You're Most Grateful For In This Current Moment.", wildcard: true },
  { id: 104, text: "Apologize To Someone In The Group For Something Big Or Small.", wildcard: true },
  { id: 105, text: "Ask A Question You'd Be Too Afraid To Ask.", wildcard: true },
  { id: 106, text: "Ask Literally Anything. Permission To Go There.", wildcard: true },
  { id: 107, text: "Call Someone You Admire And Tell Them Why You Appreciate Them! Put On Speaker Phone.", wildcard: true },
  { id: 108, text: "Create A Secret Handshake.", wildcard: true },
  { id: 109, text: "Dare Your Partner To Do Something Outside Of Their Comfort Zone In The Next Week.", wildcard: true },
  { id: 110, text: "Do Your Best Impersonation Of Each Other.", wildcard: true },
  { id: 111, text: "Draw A Picture Together. 30 Seconds.", wildcard: true },
  { id: 112, text: "Draw Your Current Mood. Compare.", wildcard: true },
  { id: 113, text: "Give Your Partner A Hug. Not The Crappy Kind. A Warm Fluffy One.", wildcard: true },
  { id: 114, text: "If We Had To Try Something New Tonight, What Would It Be? Bonus: Do It.", wildcard: true },
  { id: 115, text: "Look In The Mirror Today And Give Yourself A Genuine Compliment.", wildcard: true },
  { id: 116, text: "Maintain Eye Contact For 30 Seconds. What Did You Notice?", wildcard: true },
  { id: 117, text: "Make An Assumption About Me. All Players.", wildcard: true },
  { id: 118, text: "Play A Round Of Rock Paper Scissors. Loser Must Do Anything Their Partner Wants.", wildcard: true },
  { id: 119, text: "Press Shuffle On Your Music Library. Explain The First Song That Comes Up!", wildcard: true },
  { id: 120, text: "Rate Your Dancing Skills On A Scale Of 1-10. All Players.", wildcard: true },
  { id: 121, text: "Scroll Through Each Other's Instagrams. Find The Picture You Feel Best Represents Your Partner.", wildcard: true },
  { id: 122, text: "Share A Life Update With The Rest You Would Usually Just Keep To Yourself.", wildcard: true },
  { id: 123, text: "Share Your Screen Time. All Players.", wildcard: true },
  { id: 124, text: "Show The First Photo In Your Camera Roll. Explain.", wildcard: true },
  { id: 125, text: "Sing The Chorus Of Your Favorite Song Of All Time. Get Into It!", wildcard: true },
  { id: 126, text: "Staring Contest. First One To Laugh Has To Finish Their Drink.", wildcard: true },
  { id: 127, text: "Swap Seats With Your Partner.", wildcard: true },
  { id: 128, text: "Take 3 Deep Breaths Before Answering The Next Question.", wildcard: true },
  { id: 129, text: "Take A Family Selfie! Bonus: Send It To Someone Who Wishes Were Here.", wildcard: true },
  { id: 130, text: "Tell The Person Across From You The Biggest Lesson You've Learned From Them.", wildcard: true },
  { id: 131, text: "Think Of A Movie That Always Makes You Cry. Say Answers Out Loud.", wildcard: true },
  { id: 132, text: "Write A Note To Your Future Self. Fold And Place Somewhere Safe.", wildcard: true },
  { id: 133, text: "Write Down 3 Things You Love About Yourself Physically.", wildcard: true },
  { id: 134, text: "Write Down A Goal For This Year. Fold & Exchange. Hold Each Other Accountable.", wildcard: true },
  { id: 135, text: "Write Down Your Top 2 Relationship Deal Breakers. Compare.", wildcard: true },
  { id: 136, text: "Write Your Partner A Text Outside Of Your Comfort Zone At This End Of This Date.", wildcard: true }
];